### ISSUE TITLE
Process FRB events from CHIME 

### ISSUE THREAD

**Issue by Dylanb-dev** [ADACS-Australia/mwa_trigger#103]
A new system for FRB will be available soon, test using CHIME events in the meantime.

- [x] Sign up to subscribe to CHIME events
- [ ] We receive CHIME events
- [ ] CHIME events are able to be used in proposals

**Comment by PaulHancock** [comment]
Details on the format of CHIME events and how to subscribe are here:  https://www.chime-frb.ca/voevents

**Comment by PaulHancock** [comment]
Also will need to ingest events from ASKAP

**Comment by Dylanb-dev** [comment]
Update from CHIME, they are transferring authorship of the VOEvents Service and we should be able to receive events on 06 Feb.

https://github.com/chime-frb-open-data/community/issues/79#issuecomment-1412113357

**Comment by PaulHancock** [comment]
Closed as no longer a priority
