### ISSUE TITLE
Improve UX for event log

### ISSUE THREAD

**Issue by PaulHancock** [ADACS-Australia/mwa_trigger#106]
When filtering events using the [event log](https://tracet.duckdns.org/event_log/), there are a few annoying behaviours:
- [x] Filtering by recieved/observed date
  - The start / end dates are organised horizontally, but most users expect them to be paired vertically.
  - eg. Recieved (sic) date (start) and Recieved date (end) should be in the same column instead of the same row.
- [x] When the form is submitted, the current filtering values are not shown for all values.
  - Source type will persist through submission
  - start/end dates will not persist
  - Others need testing
- [x] Fix the spelling error above.
- [x] Sequence number appears to always be blank, maybe remove this column and filter

**Comment by Dylanb-dev** [comment]
>Sequence number appears to always be blank, maybe remove this column and filter

Only shows for not ignored Fermi events
