### ISSUE TITLE
Update proposal descision details log to be more human readable

### ISSUE THREAD

**Issue by PaulHancock** [ADACS-Australia/mwa_trigger#120]
The log on page https://tracet.duckdns.org/proposal_decision_details/2824/ is a little wrangled and needs some TLC.

**Comment by Dylanb-dev** [comment]
https://github.com/ADACS-Australia/TraceT/commit/faf97dd5225fd4de1981109ddd9aac89fdc83ed9

**Comment by Dylanb-dev** [comment]
seems to be working without issue now
