### ISSUE TITLE
Parsing SWIFT XRT Pos VOEvents

### ISSUE THREAD

**Issue by NickSwainston** [ADACS-Australia/mwa_trigger#41]
There are two problems with the XRT pos files and our current implementation
1. There is no "GRB_Identified" field in the XML files so we can't (by itself) tell that it's a GRB trigger. We have to check if the trigger ID had a previous GRB detection. There are checks that prevent source types (in this case None) that aren't on the proposal from triggering. We would have to code a solution around this
2. The is no duration in the XML file. The logic normally checks if the duration is within the triggering limits so would we once again have to code around this for just these event types or all reporting checks? We may also need it if the previous trigger was ignored because it was not accurate enough

**Comment by PaulHancock** [comment]
`SWIFT_XRT_Pos` events should be grouped with previous BAT alert events. This will make both issues here easier to deal with. Related to #46
