### ISSUE TITLE
New menu item on home title bar: recent events

### ISSUE THREAD

**Issue by PaulHancock** [ADACS-Australia/mwa_trigger#61]
Have a link from the home page that goes to a pre-filtered version of the VOEvent log with the telescope info already set.

Example: A drop down titled "recent events", which has links to "SWIFT, Fermi, LVC, all". The "all" link is the same as the current unfiltered VOEvents log page.

Related to https://github.com/ADACS-Australia/mwa_trigger/issues/56#issuecomment-1184158853

**Comment by NickSwainston** [comment]
I don't think this is worth making a new navbar item but I can add a telescope filter to the event group log/list page

**Comment by PaulHancock** [comment]
Updated user story
- A link to most recent event groups from the home page
- want to click a button to see all event groups
  - and then filter to look for types of events
  - the "full event group log" button should go to a more full version of the table on the front page
  - Needs to filter on "real events" as if we have selected ignored=No
  - Need to be able to filter on event types (eg GRB) as well as telescope (eg SWIFT).

**Comment by PaulHancock** [comment]
Completed in PR #96
