### ISSUE TITLE
review and update documentation

### ISSUE THREAD

**Issue by PaulHancock** [ADACS-Australia/mwa_trigger#65]
Ahead of the handover we need to review and update the documentation.

- [x] Define terms in a glossary
- [x] Introduce the purpose of the app
- [x] Figure out what is wrong with trigger_atca function (generates errors when making docs)

**Comment by NickSwainston** [comment]
I removed the trigger_atca function as the atca-rapid-response-api handles everything that the trigger_mwa function does. The error can likely be fixed by updating the python module or removing some old doc files
