### ISSUE TITLE
Clearer text alert

### ISSUE THREAD

**Issue by NickSwainston** [ADACS-Australia/mwa_trigger#87]
Update the text alert (and probably email) to something that indicates which proposal is triggering so

"{proposal ID}: {observing telescope} {Triggering/pending} on {event telescope} {source type}"

ATCA_HESS_GRBs: ATCA TRIGGERING on HESS GRB

ATCA_short_GRB: ATCA PENDING on SWIFT GRB

**Comment by Dylanb-dev** [comment]
[6f546d5](https://github.com/ADACS-Australia/TraceT/commit/6f546d5e12e57919861e71813dbbfbe28d00a52d)
