### ISSUE TITLE
BUG: Missing GRB events

### ISSUE THREAD

**Issue by Dylanb-dev** [ADACS-Australia/mwa_trigger#97]
Might be nimbus related issue. GRB 230116C was missed by the system? Group id 93962, event 1149250.

Can we get comet logs from 16th of jan to review for the missed event.

Is BAT_GRB_Pos is being dropped from the queue?

**Comment by Dylanb-dev** [comment]
Event from NASA
https://gcn.gsfc.nasa.gov/other/1149250.swift

Syslog indicates nimbus was functioning normally.

```
Jan 16 15:17:01 mwa-trigger CRON[13430]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan 16 15:25:01 mwa-trigger CRON[13540]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 16 15:35:01 mwa-trigger CRON[13642]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 16 15:45:01 mwa-trigger CRON[13847]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 16 15:55:01 mwa-trigger CRON[14099]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
```

Possible reason is the duration was too long (64 seconds)

**Comment by PaulHancock** [comment]
Event with triger id [1149250](https://tracet.duckdns.org/event_group_details/93962/) was not triggered because the SWIFT#BAT_GRB_Pos was never seen by tracet.

On further inspection (of event logs) we can see that the twisted/comet broker never saw the event and thus never passed it to the `upload_xml.py` script that starts the whole ingest/process/trigger flow.

The MWA did, however, see this event, and the MWA is also running twisted/comet.

**Comment by PaulHancock** [comment]
### Test the connectivity of nimbus
-> `ping -D tracet.duckdns.org  > ping.log`
-> after running over night there were no missed pings, the time for each ping was consistently 1ms, with the largest being 5ms. No packets were lost.

**Seems that the connection to nimbus isn't the problem.**

**Comment by PaulHancock** [comment]
### What messages are being lost?
Dylan runs a local development copy of `twisted_comet_wrapper.py` to see what events are received.
Compare these events to those that are listed in the `voeventdb` for the same time period:

```
end = parser.parse('2023-01-18T08:05:11+0000')
start = parser.parse('2023-01-17T04:48:28+0000')
observations = {FilterKeys.authored_since:start,
                FilterKeys.authored_until:end,
                FilterKeys.stream: 'nasa.gsfc.gcn/SWIFT'}
sent_events = apiv1.list_ivorn(filters=observations)
sent_events
```

Messages in the db = 1402
messages from swift in Dylans log = 197

**There is no obvious way to predict which messages are going to be dropped**

Connect to database:
```
sudo -u postgres psql
# list databases
\l
# connect to the one we want
\c trigger_db
# describe all tables
\d
select count(*) from trigger_app_cometlog where log like '%2023-01-16%SWIFT%';

```
There are 624 events on the 2023-01-16 which contain SWIFT.
Copy these to a csv file for analysis:
`COPY (select * from trigger_app_cometlog where log like '%2023-01-16%SWIFT%') TO '/tmp/tracet_swift.log' (FORMAT csv);`

For events between
```
start = parser.parse('2023-01-16T01:44:53+0000')
end = parser.parse('2023-01-16T23:56:41+0000')
```
There are 954 swift events in the voeventdb, and 621 logged events in tracet
there are 334 missing events

**Again, there is no clear pattern to which events will be dropped**

**Comment by PaulHancock** [comment]
## Set up a weekend run to find missing events
Running `twisted_comet_wrapper.py` on gamma crucis while connecting to 'voevent.4pisky.org' to check the incoming stream of events and compare to that which is found by the instance running on nimbus and the OG mwa instance.

From 23-01-20 -> 23-01-23 at ~9:30 am I have logs from all three locations:

- voeventdb records 3472 events in the given window
- tracet finds 2616 and missed 856 (25%)
- gamma finds 2616 and missed 856 (25%)
- mwa finds 2616 and missed 856 (25%)

For the time period in question all three instances of comet were recording the exact same stream of events, but only 75% of all events that were in the voeventdb.
the format is `Telescopes detecting | time | ivo identifier`
```
MGT 2023-01-20 00:02:34 [ivo://nasa.gsfc.gcn/AGILE#SA_Test_Pos_2023-01-20T00:02:26.00_099999-303](ivo://nasa.gsfc.gcn/AGILE#SA_Test_Pos_2023-01-20T00:02:26.00_099999-303)
MGT 2023-01-20 00:12:41 [ivo://nasa.gsfc.gcn/INTEGRAL#Point_Dir_2023-01-20T00:14:28.00_000000-334](ivo://nasa.gsfc.gcn/INTEGRAL#Point_Dir_2023-01-20T00:14:28.00_000000-334)
MGT 2023-01-20 00:21:43 [ivo://nasa.gsfc.gcn/SWIFT#Actual_Point_Dir_2023-01-20T00:21:36.48_218119236-362](ivo://nasa.gsfc.gcn/SWIFT#Actual_Point_Dir_2023-01-20T00:21:36.48_218119236-362)
MGT 2023-01-20 00:38:25+00:00 [ivo://gwnet/LVC#MS230120a-1-Preliminary](ivo://gwnet/LVC#MS230120a-1-Preliminary)
MGT 2023-01-20 00:40:17+00:00 [ivo://voeventdb.4pisky.org/subscribe-only#TestEvent-2023-01-20T00:40:17Z](ivo://voeventdb.4pisky.org/subscribe-only#TestEvent-2023-01-20T00:40:17Z)
... 2023-01-20 00:41:56 [ivo://nasa.gsfc.gcn/SWIFT#Actual_Point_Dir_2023-01-20T00:41:50.68_771848685-424](ivo://nasa.gsfc.gcn/SWIFT#Actual_Point_Dir_2023-01-20T00:41:50.68_771848685-424)
MGT 2023-01-20 00:43:01+00:00 [ivo://gwnet/LVC#MS230120a-2-Preliminary](ivo://gwnet/LVC#MS230120a-2-Preliminary)
MGT 2023-01-20 00:44:40 [ivo://nasa.gsfc.gcn/INTEGRAL#Point_Dir_2023-01-20T00:46:22.99_000000-435](ivo://nasa.gsfc.gcn/INTEGRAL#Point_Dir_2023-01-20T00:46:22.99_000000-435)
MGT 2023-01-20 00:46:57 [ivo://nasa.gsfc.gcn/Fermi#Point_Dir_2023-01-20T00:47:00.00_000000-0-442](ivo://nasa.gsfc.gcn/Fermi#Point_Dir_2023-01-20T00:47:00.00_000000-0-442)
```
Events are either being found by all telescopes or missed by all of them.

**Conclude (again) that the problem isn't the location where we are receiving the events**

**Comment by PaulHancock** [comment]
The previous note is in contrast to what we saw on the initial event at 2023-01-16 15:34:37 that triggered this issue.

**Comment by PaulHancock** [comment]
## Test for multiple successive events
Run `twistd --pidfile /tmp/twistd_comet.pid -n comet --local-ivo=ivo://mwatelescope.org/trace-t --receive --cmd=./log_xml.sh` locally which will not subscribe to any external networks but *will* respond to alerts pushed from `localhost`.
Then run `send_alert.py` to push alerts.
Send 10 alerts in as short as time as possible (3-4 / second)

**No missed alerts or collisions were found.**

**Comment by PaulHancock** [comment]
## Test for broker issues:
https://wiki.ivoa.net/bin/view/IVOA/IvoaVOEvent has a list of brokers which we can connect to. Some of these are out dated but I can connect to the following without errors:
```
VOEVENT_REMOTES = ["voevent.4pisky.org","voevent.dc3.com"]
VOEVENT_TCP = ["196.44.140.214/32","68.169.57.253","50.116.49.68"]
```

`50.116.49.68` sends mostly alerts from gwnet but also a few from fermi

including these lines in `settings.py` and re-running `twisted_comet_wrapper.py` on my local machine I can see that the `4pysky` and `dc3` brokers are sending through the same events and that comet is accepting whichever arrives first, and discarding the second. `log_xml.sh` is only being run once per event.

I am interested to see if there is a difference in the alerts seen by 4pysky and dc3 and the voeventdb.

So far my testing has revealed that the broker at "voevent.4pisky.org" is not sending all the messages that are sent by the one at "voevent.dc3.com"

During the time period `('2023-01-23T07:18:29+0000', '2023-01-23T08:19:01+0000')` there were 75 events logged in the voeventdb, all of these were recieved via the dc3 broker (ipv4=`70.167.219.235`), but 18 were **not** sent via the 4pisky broker (ipv4= `46.101.66.179`).

**The problem of missing events seems to be the fault of the broker and not our webapp or nimbus.**

- [ ]  Recommend that we subscribe to both the 4pisky and dc3 brokers to be safe

**Comment by Dylanb-dev** [comment]
We are on kafka now, can create a new issue if there are dropped events
