### ISSUE TITLE
BUG: GRB tagging for swift grb events

### ISSUE THREAD

**Issue by Dylanb-dev** [ADACS-Australia/mwa_trigger#98]
- Would like to trigger on XRT positions by swift even without the initial burst.
 - Swift doesn’t include GRB when XRT_Pos events etc of the same group

**Comment by PaulHancock** [comment]
If an XRT obs comes through but there is not "GRB alert" in the group, look for alerts in some archive ([4pisky](http://voeventdb.4pisky.org/apiv1/)) to see if we missed any.

**Comment by PaulHancock** [comment]
For example:  We missed the swift-bat-pos event for https://tracet.duckdns.org/event_group_details/93962/

**Comment by Dylanb-dev** [comment]
Should be fixed with event groups and kafka
